### ISSUE TITLE
some running problems

### ISSUE THREAD

**Issue by chaos-diabolicy** [SS47816/lidar_obstacle_detector#1]
Hey,@SS47816,I was trying to run this code with the specified dataset mai_city/bags/00.bag and the command "roslaunch lidar_obstacle_detector mai_city.launch",but there was a problem occuring.
It showed " PluginlibFactory: The plugin for class 'jsk_rviz_plugin/BoundingBoxArray' failed to load.  Error: According to the loaded plugin descriptions the class jsk_rviz_plugin/BoundingBoxArray with base class type rviz::Display does not exist. Declared types are  rviz/Axes rviz/Camera rviz/DepthCloud rviz/Effort rviz/FluidPressure rviz/Grid rviz/GridCells rviz/Illuminance rviz/Image rviz/InteractiveMarkers rviz/LaserScan rviz/Map rviz/Marker rviz/MarkerArray rviz/Odometry rviz/Path rviz/PointCloud rviz/PointCloud2 rviz/PointStamped rviz/Polygon rviz/Pose rviz/PoseArray rviz/PoseWithCovariance rviz/Range rviz/RelativeHumidity rviz/RobotModel rviz/TF rviz/Temperature rviz/WrenchStamped rviz_plugin_tutorials/Imu" 
If you have any fixes please show me what to do with this issue.Thanks a lot!

**Comment by SS47816** [comment]
I think this might be because you haven't installed the `jsk-rviz-plugins` pkg, try this:
```bash
# change `melodic` to your own ROS version
sudo apt install ros-melodic-jsk-rviz-plugins
```

**Comment by chaos-diabolicy** [comment]
> I think this might be because you haven't installed the `jsk-rviz-plugins` pkg, try this:
> 
> ```shell
> # change `melodic` to your own ROS version
> sudo apt install ros-melodic-jsk-rviz-plugins
> ```

I‘ve tried the command 'sudo apt install ros-melodic-jsk-rviz-plugins' several days ago,but it didn't work,either.maybe there is some other problems,thanks for your reply!
