### ISSUE TITLE
Segmentation problem

### ISSUE THREAD

**Issue by morte2025** [SS47816/lidar_obstacle_detector#2]
Thank you for your great work.  but I found the segmentaion method in your project is not very ideal when dealing with my own lidar date.

So what is the Space/Kurb segmention you mentioned in the Todos list, I can't find any reference. Than you.

**Comment by SS47816** [comment]
Hi there,

Yes, we only used RANSAC which may not work well in some places with large slopes or unevenness. 

For space/kurb segmentation method, we haven't add it into this pkg yet. But I think you might want to check out this amazing work by JKK: https://github.com/jkk-research/urban_road_filter 

Hope this answer is useful to you. 

Best regards,
Shuo
