### ISSUE TITLE
What are the parameters in compareBoxes()

### ISSUE THREAD

**Issue by YuLinxz** [SS47816/lidar_obstacle_detector#4]
Hi, I have a problem after reading your code. 
You used two parameters when calculating IoU in compareBoxes: the Percetage Displacements and the Dimension similiarity. May I ask what its actual meaning is?

**Comment by SS47816** [comment]
Hi,

Those are just the percentage changes in terms of box center displacement and box dimensions. I am using these as simple gauges to evaluate the similarities between boxes in adjacent frames.

**Comment by YuLinxz** [comment]
您好，我是徐喻琳。您的邮件我已收到，会尽快给您回复。
