### ISSUE TITLE
cannot show the bbox

### ISSUE THREAD

**Issue by blackjacket996** [SS47816/lidar_obstacle_detector#5]
Hey! I've set it up successfully, but when I r
![Uploading rviz.jpg…]()
un with mai_city dataset, it did not show the bbox, Rviz result like this

**Comment by SS47816** [comment]
Hi,

Hope you resolved your issue. Please reopen this if you still haven't fixed it.

**Comment by Farah-mohamed** [comment]
@blackjacket996 can you please say how you fixed it as I encountered the same issue ?
