### ISSUE TITLE
velodyne real data

### ISSUE THREAD

**Issue by blackjacket996** [SS47816/lidar_obstacle_detector#6]
Hey bro! I've succeed running the launch file with my real velodyne lidar, but the result shown in Rviz shows that some noise still brought some trouble. What should I do to reduce these flashing bboxes?

https://user-images.githubusercontent.com/74939393/208045761-f9ab659a-981b-4bd3-982a-02ba9144871f.mp4

**Comment by SS47816** [comment]
Hi, 

I think these flashing boxes are caused by unstable ground filtering results. You can try relaxing/adjusting the ground filtering threshold to prevent this.
