### ISSUE TITLE
how to match downsample pointcloud and original pointcloud

### ISSUE THREAD

**Issue by jjldr** [SS47816/lidar_obstacle_detector#7]
Thank you for sharing your code. In your code, before remove ground  and cluster obstacle, you downsample original pointcloud. the ground and clusters are not original, how to match downsample ground with original pointcloud

**Comment by SS47816** [comment]
Hi,

The downsampling step is just to make sure the size of the pointcloud won't be too big, and the distribution of the points in the space is more evenly. If you want to keep the original pointcloud, feel free to skip the downsampling part.

**Comment by jjldr** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by jjldr** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
