### ISSUE TITLE
Is there a ros2 version of this repo available

### ISSUE THREAD

**Issue by hsskailash** [SS47816/lidar_obstacle_detector#8]
Hello, I want to use the lidar_obstacle_detector algorithm on ros2 foxy, by connecting an ouster lidar. Can you suggest where I can get the ros2 version of this repo?

**Comment by SS47816** [comment]
Hi,

Sorry, there's currently no plan to migrate this repo to ROS2. 

However, feel free to do it yourself and let me know if you are successful!
